spring.application.name=curso

## CONFIGURACOES H2

spring.datasource.url=jdbc:h2:file:./data/meubanco
spring.datasource.username=sa
spring.datasource.password=1234
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

## CONFIGURACAO POSTGRES

#spring.datasource.url=jdbc:postgresql://pg-e7741fd-ezambomsantana-39a7.k.aivencloud.com:18245/defaultdb?sslmode=require
#spring.datasource.username=avnadmin
#spring.datasource.password=
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


## CONFIGURACOES GERAIS

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always